name: linux-cpu
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'src/**'
      - '.github/workflows/linux-cpu.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/linux-cpu.yml'

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  linux_buil_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: ./script/linux_build.sh