name: windows-cpu
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'src/**'
      - '.github/workflows/windows-cpu.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/windows-cpu.yml'

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  windows_build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build
        run: powershell .\script\windows_build.ps1