name: windows
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'src/**'
      - '.github/workflows/windows.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/windows.yml'

jobs:
  build:
    name: windows-build
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v3
      # build
      - name: build-pack
        run: |
            .\script\build.ps1
            .\script\package.ps1 package
            7z a -r package.zip package
      # upload
      - name: upload-zip
        uses: actions/upload-artifact@v3
        with:
          path: ./*.zip

  test:
    needs: build
    name: ${{ matrix.model }}-windows-test
    runs-on: windows-latest
    strategy:
      matrix:
        model: [chatglm-6b, chatglm2-6b, chatglm3-6b, codegeex2-6b, qwen-7b-chat, baichuan2-7b-chat, llama2-7b-chat]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: workspace
      - name: windows-test
        run: |
            cd workspace
            7z x package.zip
            cd package
            echo ${{ matrix.model }}
            ./script/download_model.ps1 ${{ matrix.model }}
            cd build
            .\Release\cli_demo ..\${{ matrix.model }} prompt.txt
            Exit 0
